//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_PRODUTO
    {
        public CATEGORIA_PRODUTO()
        {
            this.PRODUTOes = new HashSet<PRODUTO>();
        }
    
        public decimal ID { get; set; }
        public string NOME_CATEGORIA { get; set; }
        public short STATUS { get; set; }
        public System.DateTime DATACRIACAO { get; set; }
        public Nullable<System.DateTime> DATAALTERACAO { get; set; }
    
        public virtual ICollection<PRODUTO> PRODUTOes { get; set; }
    }
}
