//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
        }
    
        public decimal ID { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string CEP { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string TELEFONE { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
    
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
    }
}
