//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectContext : DbContext
    {
        public ProjectContext()
            : base("name=ProjectContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN_USERS> ADMIN_USERS { get; set; }
        public DbSet<CATEGORIA_PRODUTO> CATEGORIA_PRODUTO { get; set; }
        public DbSet<CLIENTE> CLIENTEs { get; set; }
        public DbSet<IMG_PRODUTO> IMG_PRODUTO { get; set; }
        public DbSet<ITEM_NF> ITEM_NF { get; set; }
        public DbSet<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public DbSet<PRODUTO> PRODUTOes { get; set; }
    }
}
