//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG_PRODUTO
    {
        public decimal ID { get; set; }
        public byte[] IMAGEM { get; set; }
        public string DESCRICAO { get; set; }
    }
}
