//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_NF
    {
        public decimal ID_NF { get; set; }
        public decimal ID_PRODUTO { get; set; }
        public decimal VALOR_UNIT { get; set; }
        public decimal ID_ITEM_NF { get; set; }
        public decimal ST_ITEM { get; set; }
    
        public virtual NOTA_FISCAL NOTA_FISCAL { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
