//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL
    {
        public NOTA_FISCAL()
        {
            this.ITEM_NF = new HashSet<ITEM_NF>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal CD_NOTA { get; set; }
        public System.DateTime DATACRIACAO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<ITEM_NF> ITEM_NF { get; set; }
    }
}
