//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public PRODUTO()
        {
            this.ITEM_NF = new HashSet<ITEM_NF>();
        }
    
        public decimal ID { get; set; }
        public string NOME { get; set; }
        public decimal VALOR_UNIT { get; set; }
        public Nullable<decimal> ID_CATEGORIA_PROD { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
        public Nullable<System.DateTime> DATAALTERACAO { get; set; }
        public Nullable<decimal> ID_IMAGEM { get; set; }
    
        public virtual CATEGORIA_PRODUTO CATEGORIA_PRODUTO { get; set; }
        public virtual ICollection<ITEM_NF> ITEM_NF { get; set; }
    }
}
